# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  version "0.10.0"

  on_macos do
    on_arm do
      sha256 "1404f7b7aca9ceec115ea88ddfc507c1c5b08e0692fad1ef70beca8a8760b830"
      url "https://github.com/bkildow/wt-cli/releases/download/v#{version}/wt-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "dd8c25b6b1384701fcf44143fa50ef0d357bbee5272e81b6d50d0826282a8b53"
      url "https://github.com/bkildow/wt-cli/releases/download/v#{version}/wt-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f0f575989ee93e9f840742586343f5217e44ae0d68f1d786772180997035fee2"
      url "https://github.com/bkildow/wt-cli/releases/download/v#{version}/wt-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dfb641a1c440d328f6ffc75f66396aaf579fecc041a21bf213a3b141179032e0"
      url "https://github.com/bkildow/wt-cli/releases/download/v#{version}/wt-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wt"
  desc "CLI for managing git worktree-based development workflows"
  homepage "https://github.com/bkildow/wt-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wt"]
    end
  end

  # No zap stanza required
end
