# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "5992d1fdaef811a6b659ed1b5df69c00ed15471e3057803ed5be53d2b1358d7f"
      url "https://github.com/bkildow/wt-cli/releases/download/v#{version}/wt-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f6f7f6eeb6f4d04b378ef55f032d163972501b4d45975ca86b1bd5e1bd7d2eb3"
      url "https://github.com/bkildow/wt-cli/releases/download/v#{version}/wt-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ffaa6874b76c029907f937251c0f5a769a7ebbcdcf86072026ab202359aaad4e"
      url "https://github.com/bkildow/wt-cli/releases/download/v#{version}/wt-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c1885ac4483a552e9aa8bf95f63e6eba4766ef2b15460e7294f305720bb7443a"
      url "https://github.com/bkildow/wt-cli/releases/download/v#{version}/wt-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wt"
  desc "CLI for managing git worktree-based development workflows"
  homepage "https://github.com/bkildow/wt-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wt"]
    end
  end

  # No zap stanza required

end
