# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "cb3d0e54dbb334f09fa420d6ada639c75c66fff488700ecb06e8d35049a4b5b3"
      url "https://github.com/bkildow/wt-cli/releases/download/v#{version}/wt-cli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3ad5b2ca07c4a506689c502c5f33ca45cd8e3f1c8e2d53f8e523f1a7a30dd887"
      url "https://github.com/bkildow/wt-cli/releases/download/v#{version}/wt-cli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "14f8ad326a75fa014504fc8a942ce14bb5a56b3b6e39cae7a2ce359a983d5f67"
      url "https://github.com/bkildow/wt-cli/releases/download/v#{version}/wt-cli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e75c7e25ebea3057e34dea56fd87327cf2eacbe17aa2432200bb0be86ffee9bc"
      url "https://github.com/bkildow/wt-cli/releases/download/v#{version}/wt-cli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wt"
  desc "CLI for managing git worktree-based development workflows"
  homepage "https://github.com/bkildow/wt-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wt"]
    end
  end

  # No zap stanza required

end
