# This file was generated by GoReleaser. DO NOT EDIT.
cask "wtx" do
  version "0.11.0"

  on_macos do
    on_arm do
      sha256 "c82702c04f858d0dfcc35712d134b8c1a69a971a002d875bad977147fa6ecf80"
      url "https://github.com/bkildow/wtx/releases/download/v#{version}/wtx_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4d2eb25e465a494f4930765f03fe4279dee6cfbf3cf212e2d504f16e628c688e"
      url "https://github.com/bkildow/wtx/releases/download/v#{version}/wtx_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2962bad6522cbcc778c5f209cddedcc73eeb04cf839817e3511b3cbe10e9f4ca"
      url "https://github.com/bkildow/wtx/releases/download/v#{version}/wtx_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "470784c420cc9e62fd4c027a4c90e9dfe85c3d15cbf65a691f547176b291dc43"
      url "https://github.com/bkildow/wtx/releases/download/v#{version}/wtx_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wtx"
  desc "CLI for managing git worktree-based development workflows"
  homepage "https://github.com/bkildow/wtx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wtx"
  binary "wt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wtx"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wt"]
    end
  end

  # No zap stanza required
end
